name: Build
on:
  release:
    types: published
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v6.2.0
      - name: Install PyInstaller
        run: pip install pyinstaller
      - name: Build
        run: python -m PyInstaller --onefile __main__.py
