name: Build
on:
  release:
    types: published
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v6.2.0
      - name: Install PyInstaller
        run: |
          pip install -r req.txt
          pip install pyinstaller
      - name: Build
        run: python -m PyInstaller --onefile __main__.py
      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # Note: Updated to v4 to match newer standards
        with:
          name: Windows
          path: dist/__main__.exe

  publish:
    runs-on: ubuntu-latest
    needs: build # Crucial: ensures this only runs after build succeeds
    if: ${{ github.event_name == 'release' }}
    steps:
      - name: Download
        uses: actions/download-artifact@v4 # Note: Updated to v4
        with:
          name: Windows
          path: dist
      
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/__main__.exe
